### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by s0**
Update license following changes to canonical license.

### CODE REVIEW

**Comment by hmakholm** [comment]
This needs a corresponding change in `odasa-buildutils/codeql-scripts/LICENSE.md` of `Semmle/code`.

**Comment by s0** [comment]
Change opened there.

**Comment by jf205** [comment]
It's also used in the help: https://git.semmle.com/Semmle/code/blob/master/documentation/restructuredtext/codeql/snippets/license-note.rst

**Comment by felicitymay** [comment]
Would it make sense to add a `CODEOWNERS` file to this repo to ensure that any changes to the license file trigger changes to related files in other repos?

**Comment by felicitymay** [comment]
> Update license following changes to canonical license.

@s0 - where is the canonical license?

**Comment by s0** [comment]
@felicitymay https://github.com/github/securitylab.github.com/blob/master/securitylab/content/pages/tools/codeql/license.mdx, which is subsequently published to https://securitylab.github.com/tools/codeql/license (and linked to from a number of places)

**Comment by felicitymay** [comment]
See: https://git.semmle.com/Semmle/code/pull/36025 for the change to the license in the CodeQL CLI itself.

**Comment by felicitymay** [comment]
Given that this change has already been merged into the Security Lab and Code repositories, it makes sense to merge this too. @adityasharad - do you have any objections?

**Pull request merged**
